;; Explicit funding only: transfers cannot mint away a custody deficit.
(impl-trait .sip-010-trait.sip-010-trait)
(define-fungible-token token)
(define-constant owner tx-sender)
(define-public (mint (amount uint) (who principal))
  (begin (asserts! (is-eq tx-sender owner) (err u401)) (ft-mint? token amount who)))
(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
  (begin (asserts! (is-eq tx-sender sender) (err u401)) (ft-transfer? token amount sender recipient)))
(define-read-only (get-name) (ok "Token"))
(define-read-only (get-symbol) (ok "TOK"))
(define-read-only (get-decimals) (ok u8))
(define-read-only (get-balance (who principal)) (ok (ft-get-balance token who)))
(define-read-only (get-total-supply) (ok (ft-get-supply token)))
(define-read-only (get-token-uri) (ok none))
