;; RV-only registry with independent current seating and historical registration.
(define-map seats principal bool)
(define-map registered principal (string-ascii 8))
(define-public (seat (who principal) (buy bool))
 (begin (map-set registered who (if buy "buy-band" "sel-band"))
 (ok (map-set seats who true))))
(define-public (retire (who principal)) (ok (map-set seats who false)))
(define-read-only (is-band-x (who principal))
 (and (default-to false (map-get? seats who))
 (is-eq (map-get? registered who) (some "buy-band"))))
(define-read-only (is-band-y (who principal))
 (and (default-to false (map-get? seats who))
 (is-eq (map-get? registered who) (some "sel-band"))))
(define-read-only (get-registered (who principal))
 (match (map-get? registered who) side (some {side: side, price: u0}) none))
