;; RV fixture: real STX transfers, deterministic injected late failures.
(impl-trait .jing-rung-deposit-trait.rung-trait)
(define-map credits principal uint)
(define-data-var total uint u0)
(define-data-var mode uint u0)
(define-public (set-mode (value uint)) (ok (var-set mode value)))
(define-read-only (credit (who principal)) (default-to u0 (map-get? credits who)))
(define-read-only (backed) (is-eq (var-get total) (stx-get-balance current-contract)))
(define-public (deposit (amount uint) (update (buff 8192)))
 (begin
  (try! (stx-transfer? amount tx-sender current-contract))
  (map-set credits tx-sender (+ amount (credit tx-sender)))
  (var-set total (+ amount (var-get total)))
  (asserts! (not (is-eq (var-get mode) u1)) (err u999))
  (asserts! (not (is-eq (var-get mode) u2)) (err u997))
  (ok { amount: amount, shares: amount, epoch: u0, stx-paid: u0, sbtc-paid: u0 })))
(define-public (withdraw (amount uint))
 (let ((member tx-sender) (have (credit tx-sender))
       (take (if (> amount have) have amount)))
  (asserts! (> take u0) (err u998))
  (map-set credits member (- have take))
  (var-set total (- (var-get total) take))
  (try! (as-contract? ((with-stx take))
    (try! (stx-transfer? take current-contract member))))
  (asserts! (not (is-eq (var-get mode) u1)) (err u999))
  (asserts! (not (is-eq (var-get mode) u2)) (err u997))
  (ok { stx: take, sbtc: u0 })))
(define-public (claim) (ok { stx: u0, sbtc: u0 }))
