import fs from 'node:fs';
import crypto from 'node:crypto';
import {applyExclusions} from './coverage-exclusions.mjs';
const dir='tests/unit/integration-v6-3',out=`${dir}/.build`;
const meta=JSON.parse(fs.readFileSync(`${out}/sources.json`,'utf8'));
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
for(const [name,m] of Object.entries(meta.sources)){
 const source=fs.readFileSync(m.path,'utf8');
 if(sha(source)!==m.sha256)throw Error(`${m.path} changed since build; rerun.`);
 let expected=source;
 if(name!=='jing-core-v6'&&name!=='jing-ladder-v1')for(const [from,to] of Object.entries(meta.substitutions))expected=expected.replaceAll(from,to);
 if(fs.readFileSync(`${out}/${name}.clar`,'utf8')!==expected)throw Error(`Unexpected source substitution: ${name}`);
}
const lcov=fs.readFileSync(`${out}/lcov.info`,'utf8');
const results=JSON.parse(fs.readFileSync(`${out}/results.json`,'utf8'));
if(!results.success||results.numFailedTests||results.numPendingTests||results.numTodoTests)
 throw Error('Coverage release report requires a complete passing run, without skipped tests.');
const metric=m=>({hit:[...m.values()].filter(n=>n>0).length,total:m.size,percent:Number((100*[...m.values()].filter(n=>n>0).length/m.size).toFixed(2))});
const contracts={};
for(const name of ['jing-buy-stx-core-spread-v1','jing-sell-stx-core-spread-v1']){
 const functions=new Map(),lines=new Map(),branches=new Map();let records=0;
 for(const record of lcov.split('end_of_record')){
  if(!record.split('\n').some(l=>l.startsWith('SF:')&&l.endsWith(`/${out}/${name}.clar`)))continue;
  records++;
  for(const line of record.split('\n')){
   const [kind,rest]=line.split(':');if(!rest)continue;const v=rest.split(',');
   const add=(m,k,n)=>m.set(k,(m.get(k)??0)+n);
   if(kind==='FN')functions.set(v[1],functions.get(v[1])??0);
   if(kind==='FNDA')add(functions,v[1],Number(v[0]));
   if(kind==='DA')add(lines,v[0],Number(v[1]));
   if(kind==='BRDA')add(branches,v.slice(0,3).join(','),v[3]==='-'?0:Number(v[3]));
  }
 }
 const source=fs.readFileSync(meta.sources[name].path,'utf8');
 const count=[...source.matchAll(/\(define-(?:public|read-only|private)\s+\(/g)].length;
 if(!records||functions.size!==count)throw Error(`Missing/incomplete rung instrumentation for ${name}: ${functions.size}/${count} functions`);
 const raw={functions:metric(functions),lines:metric(lines),branches:metric(branches)};
 const exclusions=applyExclusions(source,lines,branches);
 contracts[name]={raw,exclusions,sha256:meta.sources[name].sha256,records,functions:metric(functions),lines:metric(lines),branches:metric(branches),
  uncoveredFunctions:[...functions].filter(([,n])=>!n).map(([fn])=>fn),uncoveredLines:[...lines].filter(([,n])=>!n).map(([n])=>Number(n)),uncoveredBranches:[...branches].filter(([,n])=>!n).map(([key])=>key)};
}
const report={tests:results.numPassedTests,sources:meta.sources,contracts};
fs.writeFileSync(`${out}/coverage.json`,JSON.stringify(report,null,2)+'\n');
for(const [name,c] of Object.entries(contracts))console.log(name,JSON.stringify({functions:c.functions,lines:c.lines,branches:c.branches,uncoveredFunctions:c.uncoveredFunctions}));
const thresholds=JSON.parse(fs.readFileSync(`${dir}/coverage-thresholds.json`,'utf8'));
for(const [name,c] of Object.entries(contracts))for(const [kind,min] of Object.entries(thresholds)){
 if(c[kind].percent<min)throw Error(`${name}: ${kind} ${c[kind].percent}% is below ${min}%`);
}
const doc=['# Core-spread v1 Clarinet coverage','',`Generated by \`npm run test:v6-3:integration\`: **${report.tests}/${report.tests} passing tests**.`,
 '', 'Metrics include the declared private-helper unit cases; see [scope and remaining gaps](README.md).',
 'Gate: 100% functions / 99% executable lines / 99% reachable branches, unchanged. Raw metrics and source-anchored exceptions are shown below. See [exception rationale](README.md#coverage-exceptions). Percentages are not a proof of correctness.',
 '', '| Rung | Functions | Lines | Branches |','| --- | --- | --- | --- |'];
for(const [name,c] of Object.entries(contracts))doc.push(`| ${name} | ${c.functions.hit}/${c.functions.total} (${c.functions.percent}%) | ${c.lines.hit}/${c.lines.total} (${c.lines.percent}%) | ${c.branches.hit}/${c.branches.total} (${c.branches.percent}%) |`);
doc.push('','## Raw instrumentation (before exceptions)','','| Rung | Functions | Lines | Branches |','| --- | --- | --- | --- |');
for(const [name,c] of Object.entries(contracts))doc.push(`| ${name} | ${c.raw.functions.hit}/${c.raw.functions.total} (${c.raw.functions.percent}%) | ${c.raw.lines.hit}/${c.raw.lines.total} (${c.raw.lines.percent}%) | ${c.raw.branches.hit}/${c.raw.branches.total} (${c.raw.branches.percent}%) |`);
doc.push('','## Explicit exceptions','');
for(const [name,c] of Object.entries(contracts)){
 doc.push(`### ${name}`,'',...c.exclusions.map(e=>`- ${e.kind} \`${e.point}\`: ${e.reason}.`),'');
}
doc.push('','## Source SHA-256','',...Object.entries(meta.sources).map(([name,m])=>`- ${name}: \`${m.sha256}\`.`));
doc.push('','## Remaining instrumentation points','');
for(const [name,c] of Object.entries(contracts)){
 doc.push(`### ${name}`,'',`- Unhit lines: ${c.uncoveredLines.join(', ')||'none'}.`,`- Unhit branches (line, block, arm): ${c.uncoveredBranches.map(k=>'`'+k+'`').join(', ')||'none'}.`,'');
}
fs.writeFileSync(`${dir}/COVERAGE.md`,doc.join('\n'));
