(define-map context (string-ascii 100) { called: uint })

(define-public (update-context (function-name (string-ascii 100)) (called uint))
  (ok (map-set context function-name { called: called })))

;; the ten simnet accounts RV draws senders and principals from
(define-constant RV-ACCOUNTS (list
  'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM
  'ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5
  'ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG
  'ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC
  'ST2NEB84ASENDXKYGJPQW86YXQCEFEX2ZQPG87ND
  'ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB
  'ST3AM1A56AK2C1XAFJ4115ZSV26EB49BVQ10MGCS0
  'ST3PF13W7Z0RRM42A8VZRVFQ75SV1K26RXEP8YGKJ
  'ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP
  'STNHKEPYEPJ8ET55ZZ0M5A34J0R3N5FM2CMMMAZ6))


;; rv-* aliases latch caught property failures for invariant mode.
;; test-* returns an error on a counterexample, which RV test mode shrinks.
(define-data-var rv-valid bool true)
(define-read-only (invariant-properties) (var-get rv-valid))
(define-private (rv-check (v bool))
  (begin (var-set rv-valid (and (var-get rv-valid) v)) (if v (ok true) (err u9900))))
(define-private (rv-price (v uint))
  (if (is-eq (mod v u8) u0) u0 (+ u24000000000000 (* (mod v u16000) u1000000000))))
(define-private (rv-amount (n uint) (x bool))
  (* (mod n u20000) (if x u1 u1000)))
(define-public (test-config (pause bool) (min uint) (distance uint))
 (begin (asserts! true (err u9900))
  (begin
    ;; Explicit fuzz aids equivalent to owner setters; access control is not under test.
    (var-set paused pause)
    (var-set min-token-x-deposit (+ u1 (mod min u500)))
    (var-set min-token-y-deposit (+ u10000 (* (mod min u500) u1000)))
    (var-set distance-slots (mod distance u3))
    (ok true))))
(define-public (test-mid (raw uint))
 (begin (asserts! true (err u9900))
  (begin (try! (contract-call? .mock-lazer-oracle set-mid (+ u24000000000000 (* (mod raw u16000) u1000000000)))) (ok true))))
;; Include fees and swept dust in payouts: all outgoing assets must be
;; accounted for, in addition to member refunds and rolled live deposits.
(define-public (test-batch)
 (let ((before (get-cycle-totals (var-get current-cycle)))
       (bx (rv-balance-x current-contract)) (by (rv-balance-y current-contract)))
  (match (settle-with-refresh 0x .mock-ft "mock-ft" .mock-ft "mock-ft")
   r (let ((after (get-cycle-totals (var-get current-cycle)))
           (out-x (- bx (rv-balance-x current-contract)))
           (out-y (- by (rv-balance-y current-contract)))
           (refund-x (var-get acc-token-x-refunded))
           (refund-y (var-get acc-token-y-refunded)))
       (print {rv-success: "test-batch", out-x: out-x, out-y: out-y,
         refund-x: refund-x, refund-y: refund-y, rolled: after})
       (rv-check (and
        (>= out-x refund-x) (>= out-y refund-y)
        (is-eq (get total-token-x before)
          (+ (- out-x refund-x) (get total-token-x after) refund-x))
        (is-eq (get total-token-y before)
          (+ (- out-y refund-y) (get total-token-y after) refund-y))
        (rv-all))))
   e (ok false))))
(define-public (test-swap (raw uint) (price uint) (x bool))
 (begin (asserts! true (err u9900))
  (let ((amount (rv-amount raw x)) (limit (rv-price price))
        (net (- amount (/ (* amount u20) u10000)))
        (minimum (if x (var-get min-token-x-deposit) (var-get min-token-y-deposit))))
    (match (swap amount limit 0x .mock-ft "mock-ft" .mock-ft "mock-ft" x)
      r (begin (print {rv-success: "test-swap"}) (rv-check (and (> limit u0) (>= net minimum)))) e (ok false)))))

(define-read-only (rv-balance-x (who principal)) (unwrap-panic (contract-call? .mock-ft get-balance who)))
(define-read-only (rv-pending-x (who principal))
  (default-to u0 (get amount (map-get? token-x-pending-deposits who))))
(define-read-only (rv-owned-x (who principal))
  (+ (get-token-x-deposit (var-get current-cycle) who) (get-token-x-parked who) (rv-pending-x who)))
(define-private (rv-sum-x (who principal) (n uint)) (+ n (rv-owned-x who)))
(define-private (rv-live-x (who principal) (n uint)) (+ n (get-token-x-deposit (var-get current-cycle) who)))
(define-private (rv-row-x (who principal))
  {who: who, live: (get-token-x-deposit (var-get current-cycle) who), parked: (get-token-x-parked who), quote: (get-token-x-order who)})
(define-private (rv-positive-x (who principal))
  (match (map-get? token-x-pending-deposits who) p (> (get amount p) u0) true))
(define-private (rv-unique (who principal) (acc (list 50 principal)))
  (if (is-some (index-of? acc who)) acc (unwrap-panic (as-max-len? (append acc who) u50))))
(define-read-only (invariant-solvent-x)
  (and (>= (rv-balance-x current-contract) (fold rv-sum-x RV-ACCOUNTS u0))
       (is-eq (contract-call? .mock-ft get-minted current-contract) u0)))
(define-read-only (invariant-totals-x)
  (let ((book (get-token-x-depositors (var-get current-cycle))))
    (and (is-eq (fold rv-live-x RV-ACCOUNTS u0) (get total-token-x (get-cycle-totals (var-get current-cycle))))
         (is-eq (fold rv-live-x book u0) (fold rv-live-x RV-ACCOUNTS u0))
         (<= (len book) u50) (is-eq (len book) (len (fold rv-unique book (list)))))))
(define-read-only (invariant-pending-positive-x)
  (is-eq (len (filter rv-positive-x RV-ACCOUNTS)) (len RV-ACCOUNTS)))
(define-public (test-deposit-x (raw uint) (price uint) (peg bool))
 (begin (asserts! true (err u9900))
  (let ((amount (rv-amount raw true)) (limit (rv-price price))
        (admitted (+ (get-token-x-deposit (var-get current-cycle) tx-sender) (get-token-x-parked tx-sender) amount))
        (minimum (var-get min-token-x-deposit)))
    (match (deposit-token-x amount limit (if peg (some u20) none) .mock-ft "mock-ft")
      r (begin (print {rv-success: "test-deposit-x"}) (rv-check (and (>= admitted minimum) (> limit u0)))) e (ok false)))))
(define-public (test-cancel-x (pause bool))
 (begin (asserts! true (err u9900))
  (let ((owned (rv-owned-x tx-sender)) (before (rv-balance-x tx-sender)))
    (var-set paused pause)
    (match (cancel-token-x-deposit .mock-ft "mock-ft")
      r (begin (print {rv-success: "test-cancel-x"}) (rv-check (and (is-eq r owned) (is-eq (rv-balance-x tx-sender) (+ before owned))
          (is-eq (rv-owned-x tx-sender) u0)
          (is-none (map-get? token-x-pending-deposits tx-sender))
          (is-none (map-get? token-x-pending-limits tx-sender))
          (is-none (map-get? token-x-pending-readmits tx-sender)))))
      e (rv-check (and (is-eq owned u0) (is-eq e u1005)))))))
(define-public (test-settle-x (who principal))
 (begin (asserts! true (err u9900))
  (let ((pending (rv-pending-x who)) (owned (rv-owned-x who)) (before (rv-balance-x who))
        (rows (map rv-row-x RV-ACCOUNTS))
        (book (get-token-x-depositors (var-get current-cycle)))
        (totals (get-cycle-totals (var-get current-cycle))))
    (try! (contract-call? .mock-jing-core reset-refund))
    (match (settle-token-x-deposit who 0x .mock-ft "mock-ft")
      r (begin (print {rv-success: "test-settle-x", reason: (contract-call? .mock-jing-core get-last-refund)}) (rv-check (and (is-eq r pending) (is-none (map-get? token-x-pending-deposits who))
        (if (is-eq (contract-call? .mock-jing-core get-last-refund) "")
          (is-eq (rv-owned-x who) owned)
          (and (is-eq (rv-owned-x who) (- owned pending)) (is-eq (rv-balance-x who) (+ before pending))))
        (if (is-eq (contract-call? .mock-jing-core get-last-refund) "queue-full")
          (and (is-eq (rv-balance-x who) (+ before pending))
               (is-eq rows (map rv-row-x RV-ACCOUNTS))
               (is-eq book (get-token-x-depositors (var-get current-cycle)))
               (is-eq totals (get-cycle-totals (var-get current-cycle))))
          true))))
      e (rv-check (if (> pending u0) (or (is-eq e u1003) (is-eq e u1032) (is-eq e u1007)) (is-eq e u1030)))))))
(define-public (test-withdraw-x (raw uint))
 (begin (asserts! true (err u9900))
  (match (withdraw-token-x (rv-amount raw true) .mock-ft "mock-ft") r (begin (print {rv-success: "test-withdraw-x"}) (ok true)) e (ok false))))
(define-public (test-limit-x (price uint))
 (begin (asserts! true (err u9900))
  (match (set-token-x-limit (rv-price price) none) r (begin (print {rv-success: "test-limit-x"}) (ok true)) e (ok false))))
(define-public (test-readmit-x (who principal))
 (begin (asserts! true (err u9900))
  (match (readmit-token-x who) r (begin (print {rv-success: "test-readmit-x"}) (ok true)) e (ok false))))
(define-public (test-settle-limit-x (who principal))
 (begin (asserts! true (err u9900))
  (match (settle-token-x-limit who 0x) r (begin (print {rv-success: "test-settle-limit-x"}) (ok true)) e (ok false))))
(define-public (test-settle-readmit-x (who principal))
 (begin (asserts! true (err u9900))
  (match (settle-token-x-readmit who 0x) r (begin (print {rv-success: "test-settle-readmit-x"}) (ok true)) e (ok false))))
(define-public (test-reprice-x (price uint))
 (begin (asserts! true (err u9900))
  (match (reprice-or-swap-token-x (rv-price price) none 0x .mock-ft "mock-ft" .mock-ft "mock-ft") r (begin (print {rv-success: "test-reprice-x"}) (ok true)) e (ok false))))

(define-read-only (rv-balance-y (who principal)) (stx-get-balance who))
(define-read-only (rv-pending-y (who principal))
  (default-to u0 (get amount (map-get? token-y-pending-deposits who))))
(define-read-only (rv-owned-y (who principal))
  (+ (get-token-y-deposit (var-get current-cycle) who) (get-token-y-parked who) (rv-pending-y who)))
(define-private (rv-sum-y (who principal) (n uint)) (+ n (rv-owned-y who)))
(define-private (rv-live-y (who principal) (n uint)) (+ n (get-token-y-deposit (var-get current-cycle) who)))
(define-private (rv-row-y (who principal))
  {who: who, live: (get-token-y-deposit (var-get current-cycle) who), parked: (get-token-y-parked who), quote: (get-token-y-order who)})
(define-private (rv-positive-y (who principal))
  (match (map-get? token-y-pending-deposits who) p (> (get amount p) u0) true))
(define-read-only (invariant-solvent-y)
  (and (>= (rv-balance-y current-contract) (fold rv-sum-y RV-ACCOUNTS u0))
       (is-eq (contract-call? .mock-ft get-minted current-contract) u0)))
(define-read-only (invariant-totals-y)
  (let ((book (get-token-y-depositors (var-get current-cycle))))
    (and (is-eq (fold rv-live-y RV-ACCOUNTS u0) (get total-token-y (get-cycle-totals (var-get current-cycle))))
         (is-eq (fold rv-live-y book u0) (fold rv-live-y RV-ACCOUNTS u0))
         (<= (len book) u50) (is-eq (len book) (len (fold rv-unique book (list)))))))
(define-read-only (invariant-pending-positive-y)
  (is-eq (len (filter rv-positive-y RV-ACCOUNTS)) (len RV-ACCOUNTS)))
(define-public (test-deposit-y (raw uint) (price uint) (peg bool))
 (begin (asserts! true (err u9900))
  (let ((amount (rv-amount raw false)) (limit (rv-price price))
        (admitted (+ (get-token-y-deposit (var-get current-cycle) tx-sender) (get-token-y-parked tx-sender) amount))
        (minimum (var-get min-token-y-deposit)))
    (match (deposit-token-y amount limit (if peg (some u20) none) .mock-ft "mock-ft")
      r (begin (print {rv-success: "test-deposit-y"}) (rv-check (and (>= admitted minimum) (> limit u0)))) e (ok false)))))
(define-public (test-cancel-y (pause bool))
 (begin (asserts! true (err u9900))
  (let ((owned (rv-owned-y tx-sender)) (before (rv-balance-y tx-sender)))
    (var-set paused pause)
    (match (cancel-token-y-deposit .mock-ft "mock-ft")
      r (begin (print {rv-success: "test-cancel-y"}) (rv-check (and (is-eq r owned) (is-eq (rv-balance-y tx-sender) (+ before owned))
          (is-eq (rv-owned-y tx-sender) u0)
          (is-none (map-get? token-y-pending-deposits tx-sender))
          (is-none (map-get? token-y-pending-limits tx-sender))
          (is-none (map-get? token-y-pending-readmits tx-sender)))))
      e (rv-check (and (is-eq owned u0) (is-eq e u1005)))))))
(define-public (test-settle-y (who principal))
 (begin (asserts! true (err u9900))
  (let ((pending (rv-pending-y who)) (owned (rv-owned-y who)) (before (rv-balance-y who))
        (rows (map rv-row-y RV-ACCOUNTS))
        (book (get-token-y-depositors (var-get current-cycle)))
        (totals (get-cycle-totals (var-get current-cycle))))
    (try! (contract-call? .mock-jing-core reset-refund))
    (match (settle-token-y-deposit who 0x .mock-ft "mock-ft")
      r (begin (print {rv-success: "test-settle-y", reason: (contract-call? .mock-jing-core get-last-refund)}) (rv-check (and (is-eq r pending) (is-none (map-get? token-y-pending-deposits who))
        (if (is-eq (contract-call? .mock-jing-core get-last-refund) "")
          (is-eq (rv-owned-y who) owned)
          (and (is-eq (rv-owned-y who) (- owned pending)) (is-eq (rv-balance-y who) (+ before pending))))
        (if (is-eq (contract-call? .mock-jing-core get-last-refund) "queue-full")
          (and (is-eq (rv-balance-y who) (+ before pending))
               (is-eq rows (map rv-row-y RV-ACCOUNTS))
               (is-eq book (get-token-y-depositors (var-get current-cycle)))
               (is-eq totals (get-cycle-totals (var-get current-cycle))))
          true))))
      e (rv-check (if (> pending u0) (or (is-eq e u1003) (is-eq e u1032) (is-eq e u1007)) (is-eq e u1030)))))))
(define-public (test-withdraw-y (raw uint))
 (begin (asserts! true (err u9900))
  (match (withdraw-token-y (rv-amount raw false) .mock-ft "mock-ft") r (begin (print {rv-success: "test-withdraw-y"}) (ok true)) e (ok false))))
(define-public (test-limit-y (price uint))
 (begin (asserts! true (err u9900))
  (match (set-token-y-limit (rv-price price) none) r (begin (print {rv-success: "test-limit-y"}) (ok true)) e (ok false))))
(define-public (test-readmit-y (who principal))
 (begin (asserts! true (err u9900))
  (match (readmit-token-y who) r (begin (print {rv-success: "test-readmit-y"}) (ok true)) e (ok false))))
(define-public (test-settle-limit-y (who principal))
 (begin (asserts! true (err u9900))
  (match (settle-token-y-limit who 0x) r (begin (print {rv-success: "test-settle-limit-y"}) (ok true)) e (ok false))))
(define-public (test-settle-readmit-y (who principal))
 (begin (asserts! true (err u9900))
  (match (settle-token-y-readmit who 0x) r (begin (print {rv-success: "test-settle-readmit-y"}) (ok true)) e (ok false))))
(define-public (test-reprice-y (price uint))
 (begin (asserts! true (err u9900))
  (match (reprice-or-swap-token-y (rv-price price) none 0x .mock-ft "mock-ft" .mock-ft "mock-ft") r (begin (print {rv-success: "test-reprice-y"}) (ok true)) e (ok false))))

(define-private (rv-all)
  (and (invariant-properties) (invariant-solvent-x) (invariant-solvent-y)
    (invariant-totals-x) (invariant-totals-y)
    (invariant-pending-positive-x) (invariant-pending-positive-y)))
(define-public (test-state)
  (rv-check (rv-all)))
(define-public (test-batch-at (who principal) (x bool))
  (let ((price (if x (get-token-x-limit who) (get-token-y-limit who))))
    (asserts! (> price u0) (ok false))
    (try! (contract-call? .mock-lazer-oracle set-mid price))
    (test-batch)))
