import fs from 'node:fs';
import crypto from 'node:crypto';
const dir='tests/unit/router-v5-3',out=`${dir}/.build`;
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const meta=JSON.parse(fs.readFileSync(`${out}/source.json`,'utf8'));
for(const [name,m] of Object.entries(meta.sources)) {
  const source=fs.readFileSync(m.path,'utf8');
  if(sha(source)!==m.sha256) throw Error(`${m.path} changed; rerun tests.`);
  let expected=source;
  for(const [from,to] of Object.entries(m.substitutions)) expected=expected.replaceAll(from,to);
  const generated=fs.readFileSync(`${out}/${name}.clar`,'utf8');
  if(generated!==expected||sha(generated)!==m.generatedSha256) throw Error(`Unexpected substitution: ${name}`);
}
for(const [path,hash] of Object.entries(meta.fixtures)) if(sha(fs.readFileSync(path))!==hash) throw Error(`${path} changed; rerun tests.`);
const results=JSON.parse(fs.readFileSync(`${out}/results.json`,'utf8'));
if(!results.success||!results.numPassedTests||results.numFailedTests||results.numPendingTests||results.numTodoTests) throw Error('Report requires a complete passing run without skips.');
for(const file of fs.readdirSync(dir).filter(f=>f.endsWith('.test.ts'))) {
  if(!results.testResults.some(r=>r.name.endsWith(`/${dir}/${file}`))) throw Error(`Suite omitted: ${file}`);
}
const functions=new Map(),lines=new Map(),branches=new Map();let records=0;
for(const record of fs.readFileSync(`${out}/lcov.info`,'utf8').split('end_of_record')) {
  if(!record.split('\n').some(l=>l.startsWith('SF:')&&l.endsWith(`/${out}/router.clar`)))continue;
  records++;
  const add=(map,key,n)=>map.set(key,(map.get(key)??0)+n);
  for(const line of record.split('\n')) {
    const [kind,rest]=line.split(':');if(!rest)continue;const v=rest.split(',');
    if(kind==='FN')functions.set(v[1],functions.get(v[1])??0);
    if(kind==='FNDA')add(functions,v[1],Number(v[0]));
    if(kind==='DA')add(lines,v[0],Number(v[1]));
    if(kind==='BRDA')add(branches,v.slice(0,3).join(','),v[3]==='-'?0:Number(v[3]));
  }
}
const source=fs.readFileSync(meta.sources.router.path,'utf8');
const expected=[...source.matchAll(/^\(define-(?:public|read-only|private)\s+\(/gm)].length;
if(!records||functions.size!==expected)throw Error(`Incomplete router instrumentation ${functions.size}/${expected}`);
const metric=map=>{const hit=[...map.values()].filter(v=>v>0).length;return {hit,total:map.size,percent:Number((hit*100/map.size).toFixed(2))};};
const c={functions:metric(functions),lines:metric(lines),branches:metric(branches),
  uncoveredFunctions:[...functions].filter(([,n])=>!n).map(([k])=>k),
  uncoveredLines:[...lines].filter(([,n])=>!n).map(([k])=>Number(k)),
  uncoveredBranches:[...branches].filter(([,n])=>!n).map(([k])=>k)};
for(const [kind,min] of Object.entries({functions:100,lines:99,branches:99})) {
  if(c[kind].percent<min)throw Error(`${kind} coverage ${c[kind].percent}% is below ${min}%`);
}
const report={tests:results.numPassedTests,...meta,router:c};
fs.writeFileSync(`${out}/coverage.json`,JSON.stringify(report,null,2)+'\n');
console.log(JSON.stringify({tests:report.tests,...c},null,2));
const doc=['# Router v5-3 Clarinet coverage','',`Generated by \`npm run test:router-v5-3\`: **${report.tests}/${report.tests} passing tests**.`,
 '', 'Execution coverage of the real router with declared local dependency substitutions. See [scope and remaining gaps](README.md). No instrumentation points are excluded.',
 '', '| Metric | Hit / total | Coverage |','| --- | --- | --- |',...Object.entries(c).filter(([k])=>['functions','lines','branches'].includes(k)).map(([k,m])=>`| ${k} | ${m.hit}/${m.total} | ${m.percent}% |`),
 '', '## Source SHA-256','',...Object.entries(meta.sources).map(([name,m])=>`- ${name}: \`${m.sha256}\`.`),
 '', '## Remaining instrumentation points','',`- Unhit functions: ${c.uncoveredFunctions.join(', ')||'none'}.`,
 `- Unhit lines: ${c.uncoveredLines.join(', ')||'none'}.`,
 `- Unhit branches (line, block, arm): ${c.uncoveredBranches.map(k=>'`'+k+'`').join(', ')||'none'}.`,''];
fs.writeFileSync(`${dir}/COVERAGE.md`,doc.join('\n'));
