// Unit harness for jing-core-v6 and jing-ladder-v1 on their current bytes.
// The manifest loads both production files directly from contracts/ (no
// substitution). The only generated file is the probe: a caller fixture with
// one pass-through public per core and ladder log entrypoint, so a contract
// caller with a known code hash can exercise every entrypoint.
import fs from 'node:fs';
import crypto from 'node:crypto';
export const dir = 'tests/unit/core-ladder-v1';
export const out = `${dir}/.build`;
export const paths = {'jing-core-v6': 'contracts/jing-core-v6.clar', 'jing-ladder-v1': 'contracts/jing-ladder-v1.clar'};
// Absolute principals: a probe deployed by another account keeps the same bytes.
const deployer = 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM';
const sha = s => crypto.createHash('sha256').update(s).digest('hex');

// Minimal s-expression reader: enough for top-level define forms.
function read(src) {
  let i = 0;
  const skip = () => {
    for (;;) {
      while (i < src.length && /\s/.test(src[i])) i++;
      if (src[i] === ';') { while (i < src.length && src[i] !== '\n') i++; continue; }
      return;
    }
  };
  const form = () => {
    skip();
    if (src[i] === '(') {
      i++; const list = [];
      for (;;) { skip(); if (src[i] === ')') { i++; return list; } list.push(form()); }
    }
    if (src[i] === '"') { const s = i++; while (src[i] !== '"') i += src[i] === '\\' ? 2 : 1; i++; return src.slice(s, i); }
    const s = i; while (i < src.length && !/[\s()]/.test(src[i])) i++; return src.slice(s, i);
  };
  const forms = []; for (;;) { skip(); if (i >= src.length) return forms; forms.push(form()); }
}
const show = t => Array.isArray(t) ? `(${t.map(show).join(' ')})` : t;
const flat = t => Array.isArray(t) ? t.flatMap(flat) : [t];

// Log entrypoints: name, typed params, and whether the body checks the pause.
export function logEntrypoints(source) {
  return read(source).filter(f => f[0] === 'define-public' && f[1][0].startsWith('log-')).map(f => ({
    name: f[1][0], params: f[1].slice(1).map(([n, t]) => ({name: n, type: show(t)})),
    pauseGated: flat(f[2]).includes('check-not-paused'),
  }));
}
const proxy = (prefix, contract, e) =>
  `(define-public (${prefix}-${e.name}${e.params.map(p => ` (${p.name} ${p.type})`).join('')})\n` +
  `  (contract-call? '${deployer}.${contract} ${e.name}${e.params.map(p => ` ${p.name}`).join('')}))`;

fs.mkdirSync(out, {recursive: true});
for (const f of ['lcov.info', 'results.json', 'coverage.json']) fs.rmSync(`${out}/${f}`, {force: true});
const sources = {}, entry = {};
for (const [name, path] of Object.entries(paths)) {
  const source = fs.readFileSync(path, 'utf8');
  sources[name] = {path, sha256: sha(source)};
  entry[name] = logEntrypoints(source);
}
const probe = [
  ';; Generated by build.mjs: a caller fixture. Identical deploys share one code hash.',
  `(define-public (core-register (canonical principal)) (contract-call? '${deployer}.jing-core-v6 register canonical))`,
  '(define-public (ladder-register (side (string-ascii 8)) (price uint) (market-price uint))',
  `  (contract-call? '${deployer}.jing-ladder-v1 register side price market-price))`,
  '(define-public (ladder-register-unseated (side (string-ascii 8)) (price uint) (market-price uint))',
  `  (contract-call? '${deployer}.jing-ladder-v1 register-unseated side price market-price))`,
  ...entry['jing-core-v6'].map(e => proxy('core', 'jing-core-v6', e)),
  ...entry['jing-ladder-v1'].map(e => proxy('ladder', 'jing-ladder-v1', e)),
  '',
].join('\n');
fs.writeFileSync(`${out}/probe.clar`, probe);
// Same entrypoints, different bytes: a different code hash.
fs.writeFileSync(`${out}/probe-alt.clar`, probe + ';; alternate bytes\n');
fs.writeFileSync(`${out}/source.json`, JSON.stringify({sources, entrypoints: entry, probeSha256: sha(probe)}, null, 2) + '\n');
fs.mkdirSync(`${dir}/settings`, {recursive: true});
fs.copyFileSync('settings/Devnet.toml', `${dir}/settings/Devnet.toml`);
