// coverage-matrix.mjs
// Which error codes and which core events of markets-sbtc-stx-jing-v6 does
// at least one v6 stxer harness expect? Mechanical: every (define-constant
// ERR_* (err uNNNN)) in the market (and jing-core-v5's park/readmit codes)
// is grepped as "uNNNN" inside the v6 harness sources; every `event:
// "<name>"` printed by the market or the core is grepped as the string.
// Prints the matrix and a list of the codes / events no harness names.
//
// Run: node simulations/coverage-matrix.mjs [--md > simulations/COVERAGE.md]
import fs from "node:fs";
import path from "node:path";

const CONTRACTS = {
  "markets-sbtc-stx-jing-v6": "contracts/markets-sbtc-stx-jing-v6.clar",
  "jing-core-v5": "contracts/jing-core-v5.clar",
  "jing-ladder": "contracts/jing-ladder.clar",
  "jing-buy-stx-core-spread": "contracts/jing-buy-stx-core-spread.clar",
};
const HARNESSES = fs.readdirSync("simulations")
  .filter((f) => /^verify-(markets-v6|v6-|vault-sbtc-stx-v6)/.test(f) && f.endsWith(".js"))
  .map((f) => path.join("simulations", f));
const md = process.argv.includes("--md");
const src = Object.fromEntries(HARNESSES.map((h) => [h, fs.readFileSync(h, "utf8")]));

function codes(file) {
  const s = fs.readFileSync(file, "utf8");
  return [...s.matchAll(/\(define-constant (ERR_[A-Z_0-9]+) \(err (u\d+)\)\)/g)].map((m) => ({ name: m[1], code: m[2] }));
}
// jing-core-v5 prints for every product; keep only the events the market
// (or the ladder / rung) can trigger: the log-* functions they call
const marketCalls = new Set([...fs.readFileSync(CONTRACTS["markets-sbtc-stx-jing-v6"], "utf8").matchAll(/\.jing-core-v5 (log-[a-z0-9-]+)/g)].map((m) => m[1]));
function events(file, name) {
  const s = fs.readFileSync(file, "utf8");
  if (name !== "jing-core-v5") return [...new Set([...s.matchAll(/event: "([a-z0-9-]+)"/g)].map((m) => m[1]))];
  const out = [];
  for (const fn of [...s.matchAll(/\(define-public \((log-[a-z0-9-]+)[\s\S]*?event: "([a-z0-9-]+)"/g)]) if (marketCalls.has(fn[1])) out.push(fn[2]);
  return [...new Set(out)];
}
const hits = (needle) => HARNESSES.filter((h) => src[h].includes(needle)).map((h) => path.basename(h).replace(/^verify-|\.js$/g, ""));

const out = [];
const log = (l) => out.push(l);
log(md ? "# Coverage matrix: error codes and events vs the v6 stxer harnesses\n" : "");
log(md ? `Generated by \`simulations/coverage-matrix.mjs\` on ${new Date().toISOString().slice(0, 10)} over ${HARNESSES.length} harnesses. A code is "named" when a harness source contains its \`uNNNN\`; an event when it contains the event string. Named is not the same as asserted, but unnamed is certainly untested.\n` : "");
let missing = [];
for (const [name, file] of Object.entries(CONTRACTS)) {
  log(md ? `\n## ${name}\n\n| code | name | harnesses |\n|---|---|---|` : `\n== ${name}`);
  for (const { name: n, code } of codes(file)) {
    const h = hits(`${code})`).concat(hits(`${code}"`)).filter((v, i, a) => a.indexOf(v) === i);
    if (h.length === 0) missing.push(`${name} ${n} ${code}`);
    log(md ? `| \`${code}\` | ${n} | ${h.length ? h.join(", ") : "**none**"} |` : `${code.padEnd(7)} ${n.padEnd(28)} ${h.length ? h.join(", ") : "NONE"}`);
  }
  const evs = events(file, name);
  if (evs.length) {
    log(md ? `\n| event | harnesses |\n|---|---|` : "-- events");
    for (const e of evs) {
      const h = hits(`"${e}"`);
      if (h.length === 0) missing.push(`${name} event ${e}`);
      log(md ? `| \`${e}\` | ${h.length ? h.join(", ") : "**none**"} |` : `${e.padEnd(28)} ${h.length ? h.join(", ") : "NONE"}`);
    }
  }
}
log(md ? `\n## Not named by any harness (${missing.length})\n` : `\n== not named by any harness (${missing.length})`);
for (const m of missing) log(md ? `- ${m}` : m);
console.log(out.join("\n"));
